const lang = {
    homeTitle: 'bag air',
    homeHeading: 'Send Anything Local & Nationwide',
    homeParagraph: 'We are an app that can deliver anything big or small.',
    changesButton: 'Save changes' ,
    settingsParagraph: 'Settings',
    editParagraph: 'Edit Account',
    changePassword: 'ChangePassword',
    frequentQuestions: 'FAQ' ,
    logoutParagraph: 'Log Out' ,
    deleteParagraph: 'Delete Account' ,
    forgetPassword: 'Forgot Password?',
    passwordParagraph: 'If you have forgotten your password, enter your email address and we will send a verification code.' ,
    loginParagraph: 'Please enter your credentials to continue with your profile.' ,
    loginHeading: 'Sign in',
    loginPar: 'or',
    loginCreate: 'Create New Account',
    sendButton: 'Send',
    registerParagraph: 'Please enter the required details to create new account.',
    registerHeading: 'Sign up',
    registerAccount : 'Already have an account?' ,
    resetParagraph: ' Your new password must be different from your previous password.',
    resetPassword:'Reset Password?',
    verificationCode: 'Verification Code',
    verificationParagraph :'Please enter the verification code we sent to your email address.' ,
    validationResend: 'Didn’t receive code?' ,
    verficationSpan : 'Send Again',
};

export default lang;